name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ---------- Frontend ----------
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci --legacy-peer-deps
        env:
          NPM_CONFIG_CACHE: ${{ runner.temp }}/.npm

      # Optional Rollup fix (forces reinstall if npm skipped binaries)
      - name: Ensure Rollup binaries are installed
        working-directory: frontend
        run: npm install rollup --force

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint --if-present

      - name: Test frontend
        working-directory: frontend
        run: npm run test --if-present

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # ---------- Backend ----------
      - name: Install backend deps
        working-directory: backend
        run: npm ci --legacy-peer-deps
        env:
          NPM_CONFIG_CACHE: ${{ runner.temp }}/.npm

      - name: Test backend
        working-directory: backend
        run: npm run test --if-present

      - name: Package backend
        working-directory: backend
        run: npm run package

      # ---------- Terraform ----------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt check
        working-directory: infra
        run: terraform fmt -check

      - name: Terraform validate
        working-directory: infra
        run: terraform validate
