name: Terraform Apply (Production)

on:
  workflow_dispatch:  # ✅ Manual trigger only

jobs:
  terraform:
    name: Apply to Production
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: production  # ✅ Requires manual approval if you protect prod env

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::402298071739:role/GitHubActionsTerraformDevRole
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Cache Terraform providers
        uses: actions/cache@v4
        with:
          path: infra/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('infra/.terraform.lock.hcl') }}

      - name: Install & Build Backend
        working-directory: backend
        run: |
          set -e
          npm ci
          npm run build

      - name: Copy Built Lambda to Infra
        run: |
          mkdir -p infra/backend-dist
          cp backend/dist/tickets.js infra/backend-dist/

      - name: Terraform Init + Select Prod
        working-directory: infra
        run: |
          terraform init \
            -backend-config="bucket=hashir-tf-remote-state" \
            -backend-config="key=mini-helpdesk/prod/infra.tfstate" \
            -backend-config="region=us-east-1"

          terraform workspace select prod || terraform workspace new prod

      - name: Terraform Apply (Prod)
        working-directory: infra
        run: terraform apply -auto-approve -no-color
